### ISSUE TITLE
:muscle: Responsiveness

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#10]
_Frontend related issue_

Add responsiveness to the UI (because it kinda sucks right now).

- [Manage screen orientation](https://medium.com/flutter-community/developing-for-multiple-screen-sizes-and-orientations-in-flutter-fragments-in-flutter-a4c51b849434)
- [Flutter responsiveness](https://medium.com/flutter-community/build-responsive-uis-in-flutter-fd450bd59158)

## Tasks

- [x] Add responsiveness to all screens
- [x] Test on Samsung A3
- [x] Test on Oppo
- [x] Test on Samsung A6 (tablet)
