### ISSUE TITLE
:flower_playing_cards: Question UI

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#13]
_UI related issue_

Implement the question's interface,  and the game behavior.

When a player loads on the game page, he receives the question and must awnser the questions. When he clicks on the right awnser, the button turns green, when he clicks on the wrong awnser, the button turns red. After the player clicked, the question goes away, swipping card mode.

## Tasks

- [x] Implement question card
- [x] Implement swipping question style
- [ ] Implement right and wrong anwnsers
