### ISSUE TITLE
:question: Daily question

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#15]
_Checking issue_

Make sure the daily question system is working.

## Tasks

**Quizz creation :**

> For the next milestones purposes, maybe create a new `DailyQuizz` object that will deal with the specifics requirements for the course rules.

- [x] The app fetches the questions on the API
- [x] If null, the questions are fetch from the Trivial Pursuit API
- [x] The questions are inserted into Firestore

**Quizz awnser :**

- [x] When a player click on the question, it increments the score according to the awnser's difficulty and of course if the awnser is right
- [x] When the game is over, it prints a game over screen
- [x] The player will not be able to go back to the daily quizz

> Develop a small UI that says "You've awnser the daily questions, come back tomorrow for a new quizz"
