### ISSUE TITLE
:bust_in_silhouette: User authentication

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#16]
_Checking issue_

Check if the authentication is working well. Make sure all the instances are matching the group's requirements.

## Tasks

- [x] Login with `username` and `password`
- [x] On registration, create a new Player object
- [x] Keep track of the user informations, and score

:bulb: Implement the user profile picture, register as a 60*60 pixels base 64 image in the database.
