### ISSUE TITLE
:car: Implement all routes

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#20]
Implement all basic routes for the application. The must redirect to a page, if the page is not done yet, just display a "Work in Progress" sign. The navigation must be accessed through the entire application, from the bottom navigation bar, to the exit buttons, and others.

## Routes

**Authentication**

- Login
- Register

**Game**

- Main page
- Shootout
- Daily
- Online
- Private

**Leaderboard**

- Leaderboard

**Profile**

- Profile page
- Edit page

## Tasks

- [x] Implement the main structure of the application
- [x] Implement all routes
- [x] Implement the "WIP" UI
