### ISSUE TITLE
:bust_in_silhouette: New user auth

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#21]
Implement new user authentication.

The user can authenticate himself with the fireauth, and then a new player is created in the `users` collection. All fields are created and initialized when the user logs himself in.

## Tasks

- [x] Add Fireauth repository
- [x] Add Player model
- [x] Add the required states

> The Player must be associated with the User and accessed from the instance of the Auth class.
