### ISSUE TITLE
:grey_question: Question shootarround

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#23]
A new type of game where you just anwser the questions and another one is fetched.

## Tasks

- [ ] Create the new QuestionShootaroundGame cubit
- [ ] Reuse the Question UI
- [ ] Update the app
