### ISSUE TITLE
:building_construction: Create a game

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#6]
Create a game, that players can join, with questions, themes and timers.

## Tasks

- [ ] Join a lobby
- [ ] Start the game
- [ ] Manage player anwsers and responses
- [ ] Manages end score

:rocket: Give the player the possibility to create custom lobbies and join game with id
