### ISSUE TITLE
Add firebase menu

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#8]
_Frontend related issue_

Create a menu that leads to the following places :
- Questions : questions on the fly from the API, with a score generated from it
- Daily quizz : A set of 10 daily questions (stored in Firebase) on which the score will be evaluated
- Game : Link to a page to either join an online game, join a local game, or create a local game.

## Tasks

- [ ] Create the menu file
- [ ] Update the app to fit the new requirements
- [ ] Make sure the game part is labbeled as WIP
