### ISSUE TITLE
:question: Add daily quizz part

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/trivial_pursuit#9]
_Firebase related part_

When a user first log in, a daily quizz is beeing generated from the API, and a set a daily questions will be generated for all the users. It will allow the user to score an amount of point according to the awnsers given.

## Tasks
- [x] Generate the question list from the user that logged in
- [x] Fetch the questions
- [x] Generate the score
- [x] Recreate the list the following day
